"""add_block_drafts_table

Revision ID: 79516c7c7d4f
Revises: b1a2c3d4e5f6
Create Date: 2026-05-05 22:02:59.832767+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79516c7c7d4f'
down_revision: Union[str, None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'block_id', name='uq_block_drafts_lead_block')
    )
    with op.batch_alter_table('block_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_block_drafts_lead_id', ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_block_drafts_lead_id')

    op.drop_table('block_drafts')
    # ### end Alembic commands ###
